name: ParkourSkills
version: 1.3
main: me.skilled.parkourskills.main.Main
description: Add parkour movements to Minecraft
author: Skilled
api-version: 1.14
commands:
    parkourskills:
      usage: /<command>
      aliases: 
        - pk